### ISSUE TITLE
Return to home after some inactive period

### ISSUE THREAD

**Issue by zaveryukha** [dimaip/calendar#23]
The program shows the same state from past usage. Should be some indicator to jump to the current day or program should automatically return the user to the home screen.
![2020-04-17_18-03-42](https://user-images.githubusercontent.com/2380280/79587247-ea477980-80da-11ea-887f-90d49ae7b763.jpg)

**Comment by dimaip** [comment]
Automatic return to main screen when opening from home screen should already work.
