### ISSUE TITLE
Remove unneccessary precache file

### ISSUE THREAD

**Issue by rolandschuetz** [dimaip/calendar#340]
You are creating separate precache entries for Googel Analytics campaign paths here:
https://github.com/dimaip/calendar/blob/master/webpack.prod.js#L31

this is not necessary, since workbox has a matching rule already:
https://developers.google.com/web/tools/workbox/modules/workbox-precaching#ignore_url_parameters

**Comment by dimaip** [comment]
Oh, nicely spotted! Thanks, I love open source :)
